from collections.abc import Buffer
import json

import secrets

# NOTE: https://docs.python.org/3/library/hashlib.html
import hashlib
import os
from datetime import datetime, timezone
from typing import Generic, TypeVar, NamedTuple
from dataclasses import dataclass
from warnings import deprecated

type Point = tuple[int, int]
type PubKey = tuple[int, int]
type PrivKey = int
type Signature = tuple[int, int]

# --- secp256k1 parameters ---
P = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F
A = 0
B = 7
Gx = 55066263022277343669578718895168534326250603453777594175500187360389116729240
Gy = 32670510020758816978083085130507043184471273380659243275938904335757337482424
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141


# Elliptic curve computations (generated by ChatGPT)
def inv_mod(k: int, p: int) -> int:
    """calculates the inverse of k modulo p"""
    # TODO: Check if mathematically correct
    if k == 0:
        raise ZeroDivisionError("division by zero")
    if k < 0:
        return p - inv_mod(-k, p)
    s, old_s = 0, 1
    r, old_r = p, k
    while r != 0:
        q = old_r // r
        old_r, r = r, old_r - q * r
        old_s, s = s, old_s - q * s
    return old_s % p


# INFO: valid
def is_on_curve(point: Point | None):
    """Check if a point is on the Elliptic curve"""
    if point is None:
        return True
    x, y = point
    # Weistrass curve y^2 = x^3 + ax + b
    # NOTE: This is mathematically sound
    return (y * y - (x * x * x + A * x + B)) % P == 0


def point_add(p1: Point | None, p2: Point | None):
    """Adds two points on the elliptic curve"""
    # TODO: Check if mathematically correct
    if p1 is None:
        return p2
    if p2 is None:
        return p1
    x1, y1 = p1
    x2, y2 = p2
    if x1 == x2 and y1 != y2:
        return None
    if p1 == p2:
        m = (3 * x1 * x1 + A) * inv_mod(2 * y1, P) % P
    else:
        m = (y2 - y1) * inv_mod(x2 - x1, P) % P
    x3 = (m * m - x1 - x2) % P
    y3 = (m * (x1 - x3) - y1) % P
    return (x3, y3)


# INFO: mathematically sound, None means point to infinity
def scalar_mult(k: int, point: Point | None) -> Point | None:
    """Multiply a point on the curve by the scalar value k"""
    # Check that the point is on the curve otherwise the multiplication isn't
    # possible.
    assert is_on_curve(point)
    if k % N == 0 or point is None:
        # If k is perfectly divisible by N or now point was given, the result is None.
        # NOTE: If k is perfectly divisible by N, the result will be a None,
        # this check saves time
        return None
    if k < 0:
        # If k is negative, we simply multiply both inputs by -1 which is
        # simple to do and allows the next part of the algorithm to work.
        return scalar_mult(-k, (point[0], (-point[1]) % P))
    result = None
    addend = point
    # To calculate the result, we add point k times, effectively multiplying
    # the point by k
    while k:
        if k & 1:
            result = point_add(result, addend)
        addend = point_add(addend, addend)
        k >>= 1
    return result


# ECDSA functions: Generated by chatGPT
# INFO: valid
def sha256(b: Buffer) -> int:
    """Calculates the sha256 hash of the input as an int"""
    return int.from_bytes(hashlib.sha256(b).digest(), "big")


# INFO: Dangerous use of random, otherwise ok
def generate_keypair() -> tuple[PrivKey, PubKey]:
    """Generate a pair of keys"""
    # Take a random value between 1 and N (N not included)
    priv = secrets.randbelow(N - 1) + 1
    # Multiply the private key with G to get the pulic key
    pub = scalar_mult(priv, (Gx, Gy))
    # WARN: the public key could be None if the first parameter of scalar_mult
    # is a multiple of N
    assert pub
    return priv, pub


# INFO: issue with random but otherwise valid ECDSA
def sign_message(priv: PrivKey, message: Buffer) -> Signature:
    """Signs a message using ECDSA with sha256 as the hash function"""
    z = sha256(message)
    while True:
        k = secrets.randbelow(N - 1) + 1
        # R = (x1, y1) = kG
        R = scalar_mult(k, (Gx, Gy))
        assert R
        # r = x1 mod n
        r = R[0] % N

        # retry if r = 0
        if r == 0:
            continue

        # k^(-1)
        k_inv = inv_mod(k, N)

        # s = 1/k * (H(M) + r * a) (mod n)
        s = (k_inv * (z + r * priv)) % N

        # retry if s = 0
        if s == 0:
            continue

        # return the signature (r, s)
        return (r, s)


# WARN: not used
def verify_signature(pub: PubKey, message: Buffer, signature: Signature) -> bool:
    """Check the ECDSA signature"""
    if pub is None or not is_on_curve(pub):
        return False
    r, s = signature
    # r and s are expected to be in NN^* and mod n
    if not (1 <= r < N and 1 <= s < N):
        return False
    # compute z = H(M)
    z = sha256(message)
    # s^(-1) mod n
    s_inv = inv_mod(s, N)
    # u1 = H(M)/s (mod n)
    u1 = (z * s_inv) % N
    # u2 = r/s (mod n)
    u2 = (r * s_inv) % N
    P1 = scalar_mult(u1, (Gx, Gy))
    P2 = scalar_mult(u2, pub)
    # P = (x1, y1) = u1G + u2A
    P = point_add(P1, P2)
    if P is None:
        return False
    # check if r = x1 mod n
    return (P[0] % N) == r


def forge_signature_for_infinity_pub(message: Buffer) -> Point:
    """Generate a valid signature when public key is None"""
    z = sha256(message)
    s = 1
    s_inv = inv_mod(s, N)
    u1 = (z * s_inv) % N
    point = scalar_mult(u1, (Gx, Gy))
    assert point is not None
    return (point[0] % N, s)


######END of ECDSA

T = TypeVar("T")


@dataclass(frozen=True)
class Record(Generic[T]):
    """Class representing a value that should be serializable and deserializable
    and include a timestamp that match its creation.
    """

    data: T
    timestamp: datetime = datetime.now(timezone.utc)
    pass

    @property
    def type(self) -> str:
        return self.data.__class__.__name__

    def to_dict(self) -> dict:
        return {
            "type": self.type,
            "data": self.data,
            "timestamp": self.timestamp.isoformat(),
        }


class DoctorData(NamedTuple):
    name: str
    avs: str
    drugs: dict[str, str]


class PatientData(NamedTuple):
    name: str
    avs: str
    symptoms: dict[str, str]


def build_doctor_record() -> Record[DoctorData]:
    """Build a doctor record"""
    name = input("Patient name: ").strip()
    avs = input("Patient AVS number: ").strip()
    drugs: dict[str, str] = {}
    print("Enter drugs and dosages. Leave drug name empty to finish.")
    while True:
        drug = input("Drug name: ").strip()
        if not drug:
            break
        dosage = input("Dosage (string): ").strip()
        drugs[drug] = dosage
    return Record(data=DoctorData(name, avs, drugs))


@deprecated("old version kept for comparison")
def build_doctor_record_old() -> bytes:
    """Build a json array with the following structure
    [
        name,
        avs,
        { [drug]: dosage }
    ]
    """
    name = input("Patient name: ").strip()
    avs = input("Patient AVS number: ").strip()
    drugs = {}
    print("Enter drugs and dosages. Leave drug name empty to finish.")
    while True:
        drug = input("Drug name: ").strip()
        if not drug:
            break
        dosage = input("Dosage (string): ").strip()
        drugs[drug] = dosage
    return json.dumps([name, avs, drugs]).encode("utf-8")


def build_patient_record() -> Record[PatientData]:
    """Build a patient record"""
    name = input("Patient name: ").strip()
    avs = input("Patient AVS number: ").strip()
    symptoms: dict[str, str] = {}
    print("Enter symptoms and their temporality. Leave symptom name empty to finish.")
    while True:
        sym = input("Symptom: ").strip()
        if not sym:
            break
        temp = input("Temporality (string): ").strip()
        symptoms[sym] = temp
    return Record(data=PatientData(name, avs, symptoms))


@deprecated("old version kept for comparison")
def build_patient_record_old() -> bytes:
    """Build a json array with the following structure
    [
        name,
        avs,
        { [symptom]: temporality }
    ]
    """
    name = input("Patient name: ").strip()
    avs = input("Patient AVS number: ").strip()
    symptoms = {}
    print("Enter symptoms and their temporality. Leave symptom name empty to finish.")
    while True:
        sym = input("Symptom: ").strip()
        if not sym:
            break
        temp = input("Temporality (string): ").strip()
        symptoms[sym] = temp
    return json.dumps([name, avs, symptoms]).encode("utf-8")


def save_record_to_db(record: Record, priv: PrivKey):
    """Save a patient record to the database accompanied by its signature"""
    json_record = json.dumps(record.to_dict())
    signature = sign_message(priv, json_record.encode("utf-8"))
    entry = {
        "record": json_record,
        "signature": {"r": hex(signature[0]), "s": hex(signature[1])},
    }
    filename: str
    match record.data:
        case PatientData():
            filename = "medical_records.txt"
        case DoctorData():
            filename = "prescriptions_records.txt"
        case _:
            raise ValueError(f"Unexpected record received Record[{record.type}]")
    # WARN: The entry is appended to the file. This will result in an invalid
    # json structure which will need to be handled correctly when reading from it
    with open(filename, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")


@deprecated("old version kept for comparison")
def save_record_to_db_old(record: bytes, signature: Signature, isPatient: bool):
    """Save a patient record to the database accompanied by its signature"""
    # WARN: There is no guarantee that given signature is for the given record
    #   but this shouldn't be an issue when it comes to saving
    # WARN: The timestamps isn't part of the signature, which means that it
    #   shouldn't be interpreted as valid because the signature is
    entry = {
        "timestamp": datetime.now().isoformat(),
        "record": record.decode(),
        "signature": {"r": hex(signature[0]), "s": hex(signature[1])},
    }
    # Choose which file to use based on the isPatient flag
    filename = "medical_records.txt" if isPatient else "prescriptions_records.txt"
    # WARN: The entry is appended to the file. This will result in an invalid
    # json structure which will need to be handled correctly when reading from it
    with open(filename, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")


def compute_public_key(priv: PrivKey) -> PubKey:
    """Compute the public key of a private key"""
    pub = scalar_mult(priv, (Gx, Gy))
    assert pub is not None
    return pub


def is_valid_private_key(key: PrivKey) -> bool:
    """Check if a private key is valid with the curve"""
    return 1 <= key < N


def is_valid_public_key(pub: PubKey, priv: PrivKey | None) -> bool:
    """Check if a public key is valid
    If None is specified for the private key, this function only checks if the
    key is on the curve
    """
    return is_on_curve(pub) if priv is None else pub == compute_public_key(priv)


class InvalidPrivateKeyError(Exception):
    pass


class InvalidPublicKeyError(Exception):
    pass


def load_priv_key(path: str) -> PrivKey:
    """Load a private key from disk and check its validity
    Raises:
        FileNotFoundError: If the path doesn't lead to an existing file
        InvalidPrivateKeyError: If the key is invalid
    """
    if not os.path.exists(path):
        raise FileNotFoundError()
    with open(path, "r") as f:
        priv = int(f.read().strip(), 16)
        if not is_valid_private_key(priv):
            raise InvalidPrivateKeyError()
        return priv


def load_pub_key(path: str, priv_key: PrivKey | None) -> PubKey:
    """Load a public key from the disk and check its validity.
    Raises:
        FileNotFoundError: If the path doesn't lead to an existing file
        InvalidPublicKeyError: If the public key isn't the public key of the
            provided private key. If None is given for the private key, The only
            check is whether the public key is a point on the curve.
    """
    if not os.path.exists(path):
        raise FileNotFoundError()
    with open(path, "r") as f:
        # The public key is read as a JSON object with the keys x and y
        # containing integers in base64
        pub_data = json.load(f)
        pub = (int(pub_data["x"], 16), int(pub_data["y"], 16))
        if not is_valid_public_key(pub, priv_key):
            raise InvalidPublicKeyError()
        return pub


def generate_and_save_keys(priv_path: str, pub_path: str) -> tuple[PrivKey, PubKey]:
    if os.path.exists(priv_path):
        # NOTE: only keeping one backup since I don't want to bother with numbering
        os.replace(priv_path, priv_path + ".bak")
        print(
            f"existing private key found during generation of keys, backing up to {priv_path}.bak"
        )

    if os.path.exists(pub_path):
        # NOTE: only keeping one backup since I don't want to bother with numbering
        os.replace(pub_path, pub_path + ".bak")
        print(
            f"existing public key found during generation of keys, backing up to {pub_path}.bak"
        )

    priv, pub = generate_keypair()
    (priv_mask, pub_mask) = (0o600, 0o644)
    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC

    # Get open the file through the os api to enforce permissions on the files
    priv_fd = os.open(priv_path, flags, priv_mask)
    os.fchmod(priv_fd, priv_mask)

    with os.fdopen(priv_fd, "w") as f:
        # The private key is simply written properly in hex format
        f.write(hex(priv))

    pub_fd = os.open(pub_path, flags, pub_mask)
    os.fchmod(pub_fd, pub_mask)
    with os.fdopen(pub_fd, "w") as f:
        # The public key is saved correctly in JSON
        json.dump({"x": hex(pub[0]), "y": hex(pub[1])}, f)
    print("New keypair generated and saved.")
    return (priv, pub)


def generate_and_save_public_key(priv: PrivKey, pub_path: str) -> PubKey:
    if os.path.exists(pub_path):
        # NOTE: only keeping one backup since I don't want to bother with numbering
        os.replace(pub_path, pub_path + ".bak")
        print(
            f"existing public key found during generation of keys, backing up to {pub_path}.bak"
        )

    pub = compute_public_key(priv)
    with open(pub_path, "w") as f:
        # The public key is saved correctly in JSON
        json.dump({"x": hex(pub[0]), "y": hex(pub[1])}, f)
    return pub


def load_or_generate_keys() -> tuple[PrivKey, PubKey]:
    """This function loads an existing pair of private/public keys or generates,
    saves and return a new pair.
    """

    # Files containing the private and public keys
    priv_file = "ecdsa_private.key"
    pub_file = "ecdsa_public.key"

    try:
        priv = load_priv_key(priv_file)
    except (InvalidPrivateKeyError, FileNotFoundError) as err:
        print(
            "Your private key is invalid."
            if isinstance(err, InvalidPrivateKeyError)
            else "Missing private key"
        )
        choice = input(
            "Would you like to generate a new pair of keys? Existing keys will be backed up to [key].bak y/N: "
        )
        if not choice == "y":
            raise err
        return generate_and_save_keys(priv_file, pub_file)

    try:
        pub = load_pub_key(pub_file, priv)
    except (InvalidPublicKeyError, FileNotFoundError) as err:
        print(
            "Your public key is invalid."
            if isinstance(err, InvalidPublicKeyError)
            else "Missing public key"
        )
        choice = input("Would you like to generate the public key? y/N: ")
        if not choice == "y":
            raise err
        return (priv, generate_and_save_public_key(priv, pub_file))

    return (priv, pub)


# INFO: Risky
@deprecated("Previous implementation, preserved here for comparison")
def load_or_generate_keys_old() -> tuple[PrivKey, PubKey]:
    """This function loads an existing pair of private/public keys or generates,
    saves and return a new pair.
    """

    # Files containing the private and public keys
    priv_file = "ecdsa_private.key"
    pub_file = "ecdsa_public.key"

    if os.path.exists(priv_file) and os.path.exists(pub_file):
        # If both files exist, proceed to extract the private and public keys.
        with open(priv_file, "r") as f:
            # The private key is converted from a base16 string to an int.
            # NOTE: The fact that we strip what we read shouldn't matter unless
            # the key isn't stored properly
            priv = int(f.read().strip(), 16)
        with open(pub_file, "r") as f:
            # The public key is read as a JSON object with the keys x and y
            # containing integers in base64
            pub_data = json.load(f)
            pub = (int(pub_data["x"], 16), int(pub_data["y"], 16))
        print("Loaded existing keypair from disk.")
        # WARN: if both files exist, their value is taken as ground truth. There
        #   is no verification that the private key is in [1;N[ and that the
        #   public key is the result of priv * G
    else:
        print("No keypair found — generating new one...")
        # If any of the files do not exist we generate a new pair of keys
        priv, pub = generate_keypair()
        with open(priv_file, "w") as f:
            # The private key is simply written properly in hex format
            f.write(hex(priv))
        with open(pub_file, "w") as f:
            # The public key is saved correctly in JSON
            json.dump({"x": hex(pub[0]), "y": hex(pub[1])}, f)
        print("New keypair generated and saved.")
        # WARN: The public and private keys are both simply saved to disk
        #   without any specifications when it comes to permissions. (on linux,
        #   resulted in 644 permissions)
    return priv, pub


def main():
    print(
        "Welcome to the medical prescription app. As a patient, you can input your symptoms so that a doctor can verify them and give you a prescription. \n As doctor, you can create prescriptions for a patient. All the records are signed with the platform's private key so that doctors know they read authentic symptoms and pharmacies know they read valid prescriptions. \n"
    )
    # Load or generate keypair. We assume that the public key is safely transfered when needed (ex: for doctors to read the records or for pharamcies to validate prescriptions)
    priv, pub = load_or_generate_keys()
    print("\n\nWho are you? (this replaces a correct login with credentials)")
    print(
        "1) Doctor"
    )  # We suppose that in practice, there is a correct login with credentials
    print("2) Patient")
    choice = input("Choose 1 or 2: ").strip()
    if choice == "1":
        record = build_doctor_record()
    elif choice == "2":
        record = build_patient_record()
        # NOTE: redundant
    else:
        print("Invalid choice")
        return
    save_record_to_db(record, priv)
    print("Record signed by system and saved in DB")

    # NOTE: sanity check
    payload = json.dumps(record.to_dict()).encode("utf-8")
    assert verify_signature(pub, payload, sign_message(priv, payload))
    return


if __name__ == "__main__":
    main()
