import json
import random
import hashlib
import os
from datetime import datetime
from base64 import b64encode

# --- secp256k1 parameters ---
P = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F
A = 0
B = 7
Gx = 55066263022277343669578718895168534326250603453777594175500187360389116729240
Gy = 32670510020758816978083085130507043184471273380659243275938904335757337482424
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141

#Elliptic curve computations (generated by ChatGPT)
def inv_mod(k, p):
    if k == 0:
        raise ZeroDivisionError('division by zero')
    if k < 0:
        return p - inv_mod(-k, p)
    s, old_s = 0, 1
    r, old_r = p, k
    while r != 0:
        q = old_r // r
        old_r, r = r, old_r - q * r
        old_s, s = s, old_s - q * s
    return old_s % p

def is_on_curve(point):
    if point is None:
        return True
    x, y = point
    return (y * y - (x * x * x + A * x + B)) % P == 0

def point_add(p1, p2):
    if p1 is None:
        return p2
    if p2 is None:
        return p1
    x1, y1 = p1
    x2, y2 = p2
    if x1 == x2 and y1 != y2:
        return None
    if p1 == p2:
        m = (3 * x1 * x1 + A) * inv_mod(2 * y1, P) % P
    else:
        m = (y2 - y1) * inv_mod(x2 - x1, P) % P
    x3 = (m * m - x1 - x2) % P
    y3 = (m * (x1 - x3) - y1) % P
    return (x3, y3)

def scalar_mult(k, point):
    assert is_on_curve(point)
    if k % N == 0 or point is None:
        return None
    if k < 0:
        return scalar_mult(-k, (point[0], (-point[1]) % P))
    result = None
    addend = point
    while k:
        if k & 1:
            result = point_add(result, addend)
        addend = point_add(addend, addend)
        k >>= 1
    return result

# ECDSA functions: Generated by chatGPT
def sha256(b):
    return int.from_bytes(hashlib.sha256(b).digest(), 'big')

def generate_keypair():
    priv = random.randrange(1, N)
    pub = scalar_mult(priv, (Gx, Gy))
    return priv, pub

def sign_message(priv, message):
    z = sha256(message)
    while True:
        k = random.randrange(0, N)
        R = scalar_mult(k, (Gx, Gy))
        r = R[0] % N
        if r == 0:
            continue
        k_inv = inv_mod(k, N)
        s = (k_inv * (z + r * priv)) % N
        if s == 0:
            continue
        return (r, s)

def verify_signature(pub, message, signature):
    r, s = signature
    if not (1 <= r < N and 1 <= s < N):
        return False
    z = sha256(message)
    s_inv = inv_mod(s, N)
    u1 = (z * s_inv) % N
    u2 = (r * s_inv) % N
    P1 = scalar_mult(u1, (Gx, Gy))
    P2 = scalar_mult(u2, pub)
    P = point_add(P1, P2)
    if P is None:
        return False
    return (P[0] % N) == r

######END of ECDSA

def build_doctor_record() -> str:
    name = input('Patient name: ').strip()
    avs = input('Patient AVS number: ').strip()
    drugs = {}
    print("Enter drugs and dosages. Leave drug name empty to finish.")
    while True:
        drug = input('Drug name: ').strip()
        if not drug:
            break
        dosage = input('Dosage (string): ').strip()
        drugs[drug] = dosage
    return json.dumps([name, avs, drugs]).encode("utf-8")


def build_patient_record() -> str:
    name = input('Patient name: ').strip()
    avs = input('Patient AVS number: ').strip()
    symptoms = {}
    print("Enter symptoms and their temporality. Leave symptom name empty to finish.")
    while True:
        sym = input('Symptom: ').strip()
        if not sym:
            break
        temp = input('Temporality (string): ').strip()
        symptoms[sym] = temp
    return json.dumps([name, avs, symptoms]).encode("utf-8")

def save_record_to_db(record, signature, isPatient):
    entry = {
        "timestamp": datetime.now().isoformat(),
        "record": record.decode(),
        "signature": {"r": hex(signature[0]), "s": hex(signature[1])},
    }
    filename = "medical_records.txt" if isPatient else "prescriptions_records.txt"
    with open(filename, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")

def load_or_generate_keys():
    priv_file = "ecdsa_private.key"
    pub_file = "ecdsa_public.key"

    if os.path.exists(priv_file) and os.path.exists(pub_file):
        with open(priv_file, "r") as f:
            priv = int(f.read().strip(), 16)
        with open(pub_file, "r") as f:
            pub_data = json.load(f)
            pub = (int(pub_data["x"], 16), int(pub_data["y"], 16))
        print("Loaded existing keypair from disk.")
    else:
        print("No keypair found — generating new one...")
        priv, pub = generate_keypair()
        with open(priv_file, "w") as f:
            f.write(hex(priv))
        with open(pub_file, "w") as f:
            json.dump({"x": hex(pub[0]), "y": hex(pub[1])}, f)
        print("New keypair generated and saved.")
    return priv, pub


def main():
    print("Welcome to the medical prescription app. As a patient, you can input your symptoms so that a doctor can verify them and give you a prescription. \n As doctor, you can create prescriptions for a patient. All the records are signed with the platform's private key so that doctors know they read authentic symptoms and pharmacies know they read valid prescriptions. \n")
    # Load or generate keypair. We assume that the public key is safely transfered when needed (ex: for doctors to read the records or for pharamcies to validate prescriptions)
    priv, pub = load_or_generate_keys()
    print('\n\nWho are you? (this replaces a correct login with credentials)')
    print('1) Doctor')#We suppose that in practice, there is a correct login with credentials
    print('2) Patient')
    choice = input('Choose 1 or 2: ').strip()
    record = b""
    isPatient = True
    if choice == '1':
        record = build_doctor_record()
        isPatient = False
    elif choice == '2':
        record = build_patient_record()
        isPatient = True
    else:
        print('Invalid choice')
        return
    signature = sign_message(priv, record)
    save_record_to_db(record, signature, isPatient)
    print('Record signed by system and saved in DB')
    return


if __name__ == '__main__':
    main()
